language: python

    python:
      - "3.7"

    services:
      - mysql

    env:
      -DJANGO=2.1 DB=mysql

    before_install:
      - gem install mdl

    install:
      - pip install -r requirements.txt
      - pip install --upgrade pip
      - pip install proselint
      - pip install -q Django==2.1
      - python setup.py -q install

    before_script:
      - mysql -e 'create database test;' -u root

    script:
      - python3 manage.py test
      - proselint README.md
      - mdl README.md
